version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  proxy:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - 8080:8080
    depends_on:
      - redis 
